name: Deploy Backend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Copiar archivos al servidor (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/backend"
          rm: true
          overwrite: true
          # (Opcional) exclude: ".git,node_modules,.github"

      - name: Instalar y reiniciar con PM2 (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/backend

            # Asegurar Node (si no estuviera)
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Asegurar PM2 (si no estuviera)
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm i -g pm2
            fi

            # Instalar deps (ci con fallback)
            npm ci --omit=dev || npm install --omit=dev

            # RECREAR .env desde Secrets para que no se pierda con rm:true
            # (Agrega estos secrets en GitHub: Settings > Secrets and variables > Actions)
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "PORT=${{ secrets.PORT || 4000 }}" >> .env

            # Reiniciar / crear proceso con nombre estable
            pm2 restart backend || pm2 start server.js --name backend
            pm2 save
