name: Deploy Backend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Crear artefacto .tar.gz (excluye .git/.github/node_modules)
        run: |
          tar -czf backend.tar.gz \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            .

      - name: Copiar artefacto al servidor (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend.tar.gz"
          target: "/home/ubuntu"

      - name: Desplegar en EC2 (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu
            mkdir -p backend
            tar -xzf backend.tar.gz -C backend
            rm -f backend.tar.gz
            cat > backend/.env << 'EOF'
            MONGO_URI=${{ secrets.MONGO_URI }}
            PORT=4000
            EOF
            chmod 600 backend/.env
            cd backend
            npm ci --omit=dev
            pm2 restart backend || pm2 start server.js --name backend --node-args="-r dotenv/config"
            pm2 save
